FROM node:18.15.0-bullseye
EXPOSE 3000
ENV NODE_ENV development
ARG PNPM_VERSION=7.11.0

RUN npm i -g npm

WORKDIR /home/nextjs/app

COPY package*.json .

RUN apt update && apt -y install --no-install-recommends ca-certificates git git-lfs openssh-client curl jq cmake sqlite3 openssl psmisc python3
RUN apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}
RUN npm install
RUN npx next telemetry disable
RUN npx browserslist@latest --update-db
# need to install linux specific swc builds
RUN npm i -D @swc/cli @swc/core pnpm@${PNPM_VERSION}

COPY . .

COPY --chown=node:node . .
USER node
# RUN addgroup -g 1001 -S nodejs
# RUN adduser -S nextjs -u 1001
# USER nextjs

CMD ["npm", "run", "dev"]
